group: management
apiVersion: v1alpha1
kind: WatchTopic
name: grpcweb
spec:
  filters:
    - group: "*"
      kind: "*"
      name: "*"
      scope:
        kind: "*"
        name: "*"
      type:
      - created
      - updated
      - deleted
    - group: "*"
      kind: "*"
      name: "*"
      type:
      - created
      - updated
      - deleted